name: irods-ingest-demo

services:
    redis:
        image: redis:7

    irods-catalog:
        build:
            context: irods_catalog
        environment:
            - POSTGRES_PASSWORD=testpassword

    irods-catalog-provider:
        build:
            context: irods_catalog_provider
        healthcheck:
            test: ["CMD", "su", "-", "irods", "-c", "./irodsctl status | grep Process"]
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 20s
            start_interval: 10s
        volumes:
            - shared_volume:/data/ufs
            - minio_bucket_volume:/data/minio-s3
        depends_on:
            irods-catalog:
                condition: service_started

    ingest-celery-workers:
        build:
            context: ingest_celery_workers
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
            - IRODS_PORT=1247
            - IRODS_HOST=irods-catalog-provider
            - IRODS_USER_NAME=rods
            - IRODS_ZONE_NAME=tempZone
            - IRODS_PASSWORD=rods
        volumes:
            - shared_volume:/data/ufs
            - minio_bucket_volume:/data/minio-s3
        depends_on:
            redis:
                condition: service_started
            irods-catalog-provider:
                condition: service_healthy
        command: ["-c", "2", "--loglevel", "INFO"] # Configure Celery options here. Note: Only takes effect at container creation.

    minio:
        image: minio/minio:RELEASE.2024-06-28T09-06-49Z
        command: server --address ":19000" --console-address ":19001" /data/minio-s3
        ports:
            - "19000:19000" # This is the port to use for issuing S3 requests.
            - "19001:19001" # Change this port, if needed, to access the MinIO console webpage.
        volumes:
            - minio_bucket_volume:/data/minio-s3
        environment: 
            MINIO_ROOT_USER: irods
            MINIO_ROOT_PASSWORD: irodsadmin

volumes:
    shared_volume:
    minio_bucket_volume:
